### PR TITLE
Fixed typo in installation

### PR DESCRIPTION
**Pull request by MKegler**
Hi, thanks for setting up this awesome challenge and providing baseline tools!

I tried to fresh-install & test the framework on Linux (Ubuntu 18.04.5 LTS) and came across two minor error/typos. I believe that the below edits should fix it.

### CODE REVIEW

**Review by jonbarker68 — COMMENTED** [review]
@MKegler thanks for this. The fix in the install/ is useful, but the line in generate_HA_inputs.py is actually correct. The anech_brir stem is instructing the generator to use the *anechoic* BRIRs for making the anechoic reference signals. If it is failing for you then it will be because you don't have the anechoic BRIRs installed. They are available in clarity_CEC1_data.anechoic.v1_3.tgz on the download site. Sorry for the confusion.

**Comment by MKegler** [comment]
@jonbarker68 thanks for the quick reply. So at the time of testing, I haven't yet downloaded the official data (takes a while), but used the small test set provided in the repo. In this case, maybe it would make sense to re-name the testing data (```./data_test/clarity_data/train/rooms/brir/```) to follow the same convention (i.e. from brir_xxx to anech_brir_xxx)?

**Comment by sgraetzer** [comment]
Thanks @MKegler. Since we introduced the new anechoic brirs we haven't updated the test data accordingly. That is, the anechoic BRIRs are missing rather than incorrectly named. The check_data function will fail when applied to the test data.

**Comment by MKegler** [comment]
@sgraetzer okay, I see. The ```check_data``` is indeed failing on test data, but is that the desired outcome (was a bit confusing for me when I first ran the code)?

Either way, apologies for the confusion. I just reverted changes in ```SceneGenerator```.

**Comment by jonbarker68** [comment]
No, it's not desired for the check_data to fail :). Looks like we need to add some dummy anech_brir_xxx signals to the test_data to fix this. We'll fix this in the next commit to avoid confusing others. Thanks for spotting this.

**Comment by sgraetzer** [comment]
Thanks again @MKegler. These issues should be resolved now.

**Pull request closed without merging**
